### PR TITLE
fix sending attachment with buffer (allow filename)

### LINKED ISSUE #334: SendFile failed with buffer
I tried
```
const buffer = Buffer.from(<csv string>);
client.sendFile(USER_ID, buffer);
```
Then got error
```
Error: Messenger API - 100 OAuthException (#100) Incorrect number of files uploaded. Must upload exactly one file.
    at handleError (/Users/dvlab/Desktop/CHT-bot/node_modules/messaging-api-messenger/lib/MessengerClient.js:63:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Error Message -
  Messenger API - 100 OAuthException (#100) Incorrect number of files uploaded. Must upload exactly one file.

Request -
  POST https://graph.facebook.com/v2.11/me/messages?access_token=<access_token>

Request Data -
  {
    "_overheadLength": 474,
    "_valueLength": 107,
    "_valuesToMeasure": [],
    "writable": false,
    "readable": true,
    "dataSize": 0,
    "maxDataSize": 2097152,
    "pauseStreams": true,
    "_released": true,
    "_streams": [],
    "_currentStream": null,
    "_boundary": "--------------------------416666756942652263281922",
    "_events": {},
    "_eventsCount": 0
  }

Response -
  400 Bad Request

Response Data -
  {
    "error": {
      "message": "(#100) Incorrect number of files uploaded. Must upload exactly one file.",
      "type": "OAuthException",
      "code": 100,
      "error_subcode": 2018005,
      "fbtrace_id": "EUKH++BUy3l"
    }
  }
```

### PR DESCRIPTION
**Pull request by chentsulin**
Should fix #334

### CODE REVIEW

File: packages/messaging-api-messenger/src/Messenger.js [hunk 1]
```diff
@@ -90,7 +91,7 @@ function createMessageFormData(
   const formdata = new FormData();
 
   formdata.append('message', JSON.stringify(message));
-  formdata.append('filedata', filedata);
+  formdata.append('filedata', filedata, omit(options, ['quick_replies']));
```
Comment (tw0517tw) [inline packages/messaging-api-messenger/src/Messenger.js]: omit `quick_replies` or pick `filename`?

Comment (chentsulin) [reply packages/messaging-api-messenger/src/Messenger.js]: It looks like we should allow all of possible fields:

```js
form.append('file', stdout, {
    filename: 'unicycle.jpg', // ... or:
    filepath: 'photos/toys/unicycle.jpg',
    contentType: 'image/jpeg',
    knownLength: 19806
  });
```

So just pass through other unknown keys.

Comment (tw0517tw) [reply packages/messaging-api-messenger/src/Messenger.js]: ok lgtm
